### ISSUE TITLE
Fix linting errors ( evaluated and way ahead)

### ISSUE THREAD

**Issue by lukemalinowski** [mitre/heimdall-vue#42]
```npm run lint``` throws a variety of linter errors. All developers are advised to fix them as they see them.

**Comment by lukemalinowski** [comment]
I'm self assigned to the issue to support fixing historical linter issues.

**Comment by james-garriss** [comment]
Still throwing an error:  https://travis-ci.com/mitre/heimdall-vue/builds/117717434
