### ISSUE TITLE
Integrate the vuesax admin starter template to align with component development

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall-vue#48]
Create a branch in integrate in the admin template and update the primary layout to use the grid system preferably tailwind, update the drop-down menu to use the sidebar.

**Comment by lukemalinowski** [comment]
@cjdoherty is taking README, package.json, App.vue for now, App.vue navbar needs to be moved into layouts/main/something

**Comment by lukemalinowski** [comment]
Also need to merge store, they were seperate files src/store/store.js and src/store.js
