### ISSUE TITLE
Reject non-JSON test files.

### ISSUE THREAD

**Issue by james-garriss** [mitre/heimdall-vue#53]
The "Select File" button allows users to select any type of file.  Images, installers, Word docs, whatever.  If the user selects anything other than a JSON file, it should fail fast and politely warn the user to select the right type of file.

Related to https://github.com/mitre/heimdall-vue/issues/17

#17

**Comment by james-garriss** [comment]
It should probably not display all the empty, non-functional components.  I think just the polite error is sufficient.

**Comment by lukemalinowski** [comment]
James, is it considered acceptable to just check the file suffix? Since, only windows, maybe OSX respects them? 

In which case we could just have an alert asking if people really want to upload the file, based on suffix. And then if we fail to parse it as json then we throw a real error?

**Comment by aaronlippold** [comment]
Given that we will probably use the file uploader component in the admin
template we should see what properties it has to restrict files.
