### ISSUE TITLE
Plug Treemap into Vuex

### ISSUE THREAD

**Issue by lukemalinowski** [mitre/heimdall-vue#70]
Create a new vuex module for all the functions that Treemap wants to use, they are:

```
getImpactFilter
getNistHash
getSearchTerm
getStatusFilter
setImpactFilter
setSearchTerm
setSelectedControl
setSelectedFamily
setSelectedSubFamily
setStatusFilter
```

**Comment by aaronlippold** [comment]
These would all be getters and setters correct?
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
